name: QA env

on: 
  push:
    branches: [ qa ]


jobs:
   build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.QA_HOST }}
        username: ${{ secrets.QA_USER }}
        key: ${{ secrets.QA_SECRET }}
        script: |
            cd public_html
            git pull origin qa

        
        